version: "3.8"

networks:
    mt-network:
        driver: bridge
services:
    mt5-app:
        image: asc686f61/fx-mt5:20241116
        container_name: mt5-app
        environment:
            - ACCOUNT=7300401
            - PASSWORD=1@NGeF3vvh7mIy
            - SERVER=ICMarketsSC-MT5-2
        deploy:
            replicas: 1
        networks:
            - mt-network
        ports:
            - "8080:8080"
            - "18812:18812"
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080"]
            interval: 10s
            retries: 3

    mt5-python:
        build:
            context: .
            dockerfile: mt5-python.Dockerfile
        depends_on:
            - mt5-app # make sure mt5-app go first!
        networks:
            - mt-network
        environment:
            - MT5_HOST=mt5-app
        ports:
            - "8000:8000"
        container_name: mt5-python
        restart: unless-stopped
